### ISSUE TITLE
Retry call in case of SSL error

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#76]
Sometimes we get the following error when trying to call the Twinfield API:

```
Error: Uncaught ErrorException: SoapClient::__doRequest(): SSL: Connection reset by peer in /somepath/vendor/php-twinfield/twinfield/src/Services/ProcessXmlService.php:53
Stack trace:
#0 [internal function]: {closure}(2, 'SoapClient::__d...', '/somepath/vendo...', 53, Array)
#1 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://account...', 'http://www.twin...', 1, 0)
#2 /somepath/vendor/php-twinfield/twinfield/src/Services/ProcessXmlService.php(53): SoapClient->__call('ProcessXmlStrin...', Array)
#3 /somepath/vendor/php-twinfield/twinfield/src/ApiConnectors/BaseApiConnector.php(44): PhpTwinfield\Services\ProcessXmlService->sendDocument(Object(PhpTwinfield\DomDocuments\BankTransactionDocument))
#4 /somepath/vendor/php-twinfield/twinfield/src/ApiConnectors/BankTransactionApiConnector.php(56): PhpTwinfield\ApiConnectors\BaseApiConnector->sendXmlDocument(Ob in /somepath/vendor/php-twinfield/twinfield/src/Services/ProcessXmlService.php:53
```

When we try the request again, it just completes successfully. It would be nice if we could retry the request in this client.

**Comment by mvdpanne** [comment]
I take it you mean automatically retrying whenever this exception pops up?

**Comment by Daanvm** [comment]
Yes.
